### ISSUE TITLE
What is the release policy?

### ISSUE THREAD

**Issue by vojta001** [rycee/home-manager#1032]
Could you please clarify, what the policy for backporting changes from master to release branches is? If you don't mind, I think it should be added to the README. The only mention I could find is #944, but it doesn't seem very official. And if it is, I would like to ask why it is like so.
I contributed with the readline package recently, mainly because it was useful for me, and therefore began using home-manager from master branch on NixOS 19.09. It worked perfectly, until a change related to GPG compatible with unstable NixOS only was merged to home-manager and therefore my configuration couldn't be built. I understand this is a minor issue, I can simply keep my own fork, but generally I feel like home-manager is a great tool developing very rapidly and having to wait for a new release or having to use unstable NixOS is unnecessary for changes that can be ported one-to-one.
Or if you just feel like it is too much work, would you mind us, the contributors, to open PRs to the latest release branch with changes from master we find relevant?
Thanks in advance

**Comment by rycee** [comment]
I guess the policy is

1. Bug fixes and minor changes that are relevant to the stable version are backported, either as soon as possible for critical bugs or in a batch whenever I have the time for non-critical ones.
2. New modules and major changes are only backported on request and if they are unlikely to cause issues for other users. Since backporting is generally a quick operation it is sufficient to create an issue.

I'll take this issue to be a request for backporting the readline module and will see about getting it into the 19.09 branch 🙂

**Comment by vojta001** [comment]
Thanks for the answer.

Is #1046 acceptable for you?

**Comment by rycee** [comment]
Closing since the PR got merged.
