### ISSUE TITLE
udiskie fails with latest nixos-unstable

### ISSUE THREAD

**Issue by pmiddend** [rycee/home-manager#1042]
The command line I'm getting for udiskie is:

```
/nix/store/cc09cv0na2zcvj1yzqdif0y0mkzba4i3-udiskie-2.1.0/bin/udiskie -2 -a -n -s 
```

which, with nixos-unstable (udiskie version 2.1.0) simply results in:

```
Usage:
    udiskie [options]
    udiskie (--help | --version)
```

Apparently the `-2` flag is the culprit, which was removed in 2.0.0 (see [the changelog])(https://github.com/coldfix/udiskie/blob/master/CHANGES.rst). Removing that solves the issue for me. I would just make a PR that removes the flag, but I'm not the author of the udiskie home manager integration and I'm not sure if that causes problems for people with older Nix channel versions.

**Comment by rycee** [comment]
It should be safe to make this change in the master branch of HM since that tracks changes in Nixpkgs master. We make no guarantee that the HM master works with older Nixpkgs versions.

The only change needed is to remove `-2` from the

    ExecStart = "${pkgs.udiskie}/bin/udiskie -2 ${commandArgs}";

line? If so then I can make a quick commit to fix it, no need for a PR.

**Comment by pmiddend** [comment]
@rycee Yes, that is all that's needed to fix the problem.

**Comment by rycee** [comment]
Cool. Should be sorted now.
