### ISSUE TITLE
Home-manager doesn't find package that nix-env finds?

### ISSUE THREAD

**Issue by TannerYoung** [rycee/home-manager#1104]
I'm new to nix so apologies if this should be self evident:

home.nix
```
{ pkgs, ... }:     
                    
{                       
  home.packages = [
    pkgs.dolphin-emu
  ]
}
```

```
> nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable

> nix-env -qa dolphin-emu
dolphin-emu-5.0
dolphin-emu-5.0
dolphin-emu-5.0-10879
dolphin-emu-5.0-11608

> home-manager switch
error: attribute 'dolphin-emu' missing, at /home/$USER/.config/nixpkgs/home.nix
```

I've used this for plenty of other pkgs, but can't get it work here?

nix-env -i dolphin-emu works for me, is there some way I should declare it that I'm not understanding?

**Comment by rycee** [comment]
Unfortunately Nix is a bit confusing in this area since a package typically is associated with three different names, see [Package naming](https://nixos.org/nixpkgs/manual/#sec-package-naming).

Basically, the plain `nix-env -i` command works with the package's _derivation name_ and Home Manager works exclusively with it's _attribute name_. In general, when you are referring to packages inside Nix code then you use attribute names because they are the native Nix concept.

To find the attribute name of a package it is easiest to use the `nix search` command. E.g.,
```console
$ nix search dolphin-emu
* nixpkgs.dolphinEmu (dolphin-emu)
  Gamecube/Wii/Triforce emulator for x86_64 and ARMv8

* nixpkgs.dolphinEmuMaster (dolphin-emu)
  Gamecube/Wii/Triforce emulator for x86_64 and ARMv8
```
so in your Home Manager configuration you can put
```
home.packages = [ pkgs.dolphinEmu ];
```
