### ISSUE TITLE
why can't we set home.path as a nix path ?

### ISSUE THREAD

**Issue by teto** [rycee/home-manager#113]
any reason ? it generates
`error: The option value `programs.home-manager.path' in `<unknown-file>' is not a null or string.`

**Comment by rycee** [comment]
I'm not certain what you mean. Can you paste the relevant lines from your configuration?

**Comment by teto** [comment]
by nix path I mean the nix type of the variable; if it starts with / or ./ or ../ it is of type 'path'
```
  programs.home-manager = {
    enable = true;
    # path = https://github.com/rycee/home-manager/archive/master.tar.gz;
    path =  /home/teto/dotfiles/home-manager;
  };
```
but it seems like it only accepts a string such as "/home/teto/dotfiles/home-manager"
```
nix-shell ~/dotfiles/home-manager -A install --run 'home-manager switch'
error: The option value `programs.home-manager.path' in `<unknown-file>' is not a null or string.
(use ‘--show-trace’ to show detailed location information)

There is an unread and relevant news item.
Read it by running the command 'home-manager news'.
```
By the way it could be nice if the --show-trace could be forwarded one way or another. If I add it to my home-manager (hm) command line, hm prints the help

**Comment by rycee** [comment]
Ah, right. Then I understand :-)

The `programs.home-manager.path` option must be a Nix string and not a path because the `home-manager` script will use this value add to `NIX_PATH` when building the generation. For example, I have

    programs.home-manager.path = "$HOME/devel/home-manager";

in my configuration and when home-manager runs it will add `home-manager=$HOME/devel/home-manager` to `NIX_PATH`. If a Nix path was allowed and I instead had

    programs.home-manager.path = ~/devel/home-manager;

in my configuration, then Nix would copy this over to the Nix store and return a store path. So home-manager would end up being hard coded to add something like `home-manager=/nix/store/hashhashhashhashhashhashhashhash-home-manager` to `NIX_PATH` and any change I make in my home-manager directory would be ignored until I reinstall the home-manager command. This is quite inconvenient 😉

About `--show-trace`. It is added to the Nix commands when giving home-manager the `-v` option. The option parsing in home-manager is super simplistic so it cannot handle long options at the moment.

**Comment by teto** [comment]
maybe it could accept a nix path and use toString on it before nix puts anything in the store ? anyway that's minor. Thanks for the clear explanation. Closing this
