### ISSUE TITLE
Rename oh-my-zsh to ohMyZsh to comply NixOS/nixpkgs

### ISSUE THREAD

**Issue by BjornMelgaard** [rycee/home-manager#115]
in home-manager/modules/programs/zsh.nix

**Comment by uvNikita** [comment]
I personally think that `oh-my-zsh` name looks better and more correct in this case since it's original project name. It seems like it's common to have dashes in services and programs names in nixpkgs as well. Just some examples:

- [services.apache-kafka](https://github.com/NixOS/nixpkgs/blob/release-17.09/nixos/modules/services/misc/apache-kafka.nix)
- [programs.command-not-found](https://github.com/NixOS/nixpkgs/tree/release-17.09/nixos/modules/programs/command-not-found/command-not-found.nix)
- [services.accounts-daemon](https://github.com/NixOS/nixpkgs/tree/release-17.09/nixos/modules/services/desktops/accountsservice.nix)
- [services.bacula-sd](https://github.com/NixOS/nixpkgs/tree/release-17.09/nixos/modules/services/backup/bacula.nix)
- [services.dnscrypt-proxy](https://github.com/NixOS/nixpkgs/tree/release-17.09/nixos/modules/services/networking/dnscrypt-proxy.nix)

But I don't have very strong opinion about that and I see the point of being consistent with nixpkgs. @rycee maybe you have a particular opinion about the naming? I will be fine with either solution since both have their pros and cons.

Relevant discussion in nixpkgs: https://github.com/NixOS/nixpkgs/pull/26083.

**Comment by rycee** [comment]
Hmm, interesting observation! We're inconsistent even in Home Manager and its few modules; with command-not-found, gnome-terminal, random-background, etc. Because of this I think it would be odd to single out oh-my-zsh for renaming. In my mind it would instead make sense to make a more substantial push to rename all the offending modules. On the other hand that is more work and I'm not inclined to spend the time. Once a PR comes we can discuss 😉

My suggestion at this time is to not rename the oh-my-zsh module but at the same time decide to consistently use the camel case format for future modules. I'd be willing to update the contributing guidelines to say this.

**Comment by rycee** [comment]
Ok, I actually updated the contributing text in #131 to basically say that lower camel case should be used everywhere except when directly referring to a Nixpkgs package in which case the hyphenated style should be used. I also made a PR for the Nixpkgs documentation saying the same.

If this gets accepted then oh-my-zsh would be the appropriate module option name.

**Comment by rycee** [comment]
Merged the contribution guidelines so I'll close this with the idea that `oh-my-zsh` in this case is acceptable because it directly references the similarly named Nixpkgs package. I hope to have the NixOS documentation updated as well in the future.
