### ISSUE TITLE
Emacs user service no longer loads the normal user environment

### ISSUE THREAD

**Issue by zeonin** [rycee/home-manager#1340]
### Issue description

After updating recently, when running emacs as a service, plugins that rely on external tools fail (like `find` for straight.el, `git` for magit, and `ledger` for ob-ledger). Despite adding these packages to `programs.emacs.extraPackages`, it seems like some of the plugins (`ledger` especially) don't pick up on them. After a quick glance, it looks like the ExecStart was previously wrapped in a runtime shell, but now it invokes emacs directly.

#### Maintainer CC

@tadfisher

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.113, NixOS, 20.09.git.ae6bdcc5358 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.3`
 - channels(root): `"nixos-20.09pre229574.0a146054bdf"`
 - channels(locus): `"nix-1809-18.09.2574.a7e559a5504"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by tadfisher** [comment]
Ah, I removed the shell wrapper because I thought it was superfluous; it is for me, because my Emacs config is generated with Nix and doesn't have impure dependencies, but that's not the common case. I'll have a fix up soon, sorry about that.

In the meantime you can set `systemd.user.services.emacs.Service.ExecStart` using `mkForce` to use a shell.
