### ISSUE TITLE
Emacs service does not create socket file

### ISSUE THREAD

**Issue by mcwitt** [rycee/home-manager#1354]
### Issue description

Since 3815248 I'm having the following issue with the configuration

``` nix
{
  programs.emacs.enable = true;
  services.emacs.enable = true;
}
```
The user service appears to start and `systemd --user status emacs.service` shows it as `active (running)`, but there is no server file created at the usual location (`/tmp/emacs1000/server`), and `emacsclient` fails to connect:
```
$ emacsclient -t
/nix/store/d23fp87461xdkk4g25ky8njcbm5h46m9-emacs-26.3/bin/emacsclient: can't find socket; have you started the server?
```

I looked at 3815248 to try to understand what changed and noticed a subtle difference in the `ExecStart` attribute. When I reverted this change (https://github.com/mcwitt/home-manager/commit/a378d2bc9744b6bb083d130e2598470c5ee36806), the issue disappeared and `emacsclient` is able to connect. I'm not sure I understand why the shell wrapper was there in the first place, but seems like it might be necessary?

#### Maintainer CC

@tadfisher 

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.46, NixOS, 20.09pre230335.9480bae3370 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.09pre230335.9480bae3370"`
 - channels(matt): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by tadfisher** [comment]
Thanks, I will revert to the wrapper shell after work tonight.

**Comment by tadfisher** [comment]
Hmm, the difference is that `bash -l` performs this:

```
Make bash act as if it had been invoked as a login shell (see INVOCATION below).
```

So I'm suspecting that the service isn't inheriting some environment variable needed to create the socket file. Which is strange, because the socket file should be simply `/tmp/emacs${UID}/server` in your case.

The upstream Emacs `.service` file doesn't use a wrapper login shell to start its service: https://github.com/emacs-mirror/emacs/blob/master/etc/emacs.service

So I'm not sure why our service, which doesn't function any differently (when socket activation is not enabled, at least), requires a full login shell environment to launch a foreground daemon with the default socket.

**Comment by mcwitt** [comment]
I investigated on my side a bit more, and it seems like the problem might be that the daemon is encountering an error while loading `init.el`, and that this prevents the server from starting (though the service is still active).

Now that you mention it, I think it makes sense why we would want to run inside `bash -l`, since otherwise Emacs wouldn't have access to the login shell's `PATH` and wouldn't have access to external commands like `git` that (I think) aren't included in the minimal environment set up by systemd.

**Comment by tadfisher** [comment]
That's a good enough reason to reinstate the login shell wrapper, yes. But it still feels like a hack to work around systemd's service isolation by running a service in a login shell. Ideally we'd figure out what environment variables need to be set and set them per-service or per-user via `~/.config/environment.d`.

As far as $PATH and such from within Emacs, that can (and should!) be overridden via `exec-path`. In fact, this is done for you if you use `emacsWithPackages`, as that builds a `site-start.el` which adds your Nix profile paths to `load-path` and `exec-path` appropriately.

Musing a bit, this may be the root cause: the `site-start.el` generated by the nixpkgs Emacs derivation pulls these paths from `NIX_PROFILES`, which may not be set for the systemd user manager. @rycee, do we have a story for importing these important environment variables? `nixpkgs` uses [`system.build.setEnvironment`](https://github.com/NixOS/nixpkgs/blob/0c3a28f08f207a0b074d5ecbbed21b5b045f690f/nixos/modules/config/shells-environment.nix#L186) for this, though it's not universally used.

**Comment by rycee** [comment]
Yeah, we'll have to figure out some good way to introduce a login like environment in a service. It would be simple to do globally for all services but I would like to avoid that as long as possible.
