### ISSUE TITLE
use bind mounts instead of symlinks

### ISSUE THREAD

**Issue by nrdxp** [rycee/home-manager#1404]
I'm curious if we would be interested in implementing the files that home-manager deploys as bind mounts to their respective locations in the nix-store. This would be soley to increase determinism as it would allow the files deployed by home-manager in the users home directory to be unremoveable via normal means unless the root user umounts the bind.

This, to me, seems better than a symlink which can easily be deleted. Also, this idea follows the same symantic design as the nix/store itself which is also bind mounted for the same reason. It doesn't seem like it would be too much work to simply unbind the old generation , cleanup and then rebind the new files, unless I'm missing something.

**Comment by rycee** [comment]
Switching to using bind mounts or some other form of overlay mounts is quite unlikely since we cannot guarantee that the user has sufficient permissions to set up bind mounts within their home directory. Also, as far as I know, these would not work at all under macOS.

Some old work on improving atomicity during activation is available in #1025 but I haven't had any chance to finish up work on it.

**Comment by nrdxp** [comment]
Interesting, seems that should definitely improve things. I'll go ahead and close this. Thanks for the prompt response.
