### ISSUE TITLE
`home-manager switch` takes ages to finish up

### ISSUE THREAD

**Issue by ihsanturk** [rycee/home-manager#1421]
### Issue description
This is not happening everytime but happens often. I just came here from homebrew and want to use nixos/home-manager but looks like it is not "just works". This problem interrupts my work I just could not fix it and I cried (really) once, because of this issue. I am just adding a package, why it tries to install (and build some of the packages) every single thing on my machine or is it installs at all? what is it mean "copying path"?!! It really angered me. Sorry for bothering but this really does not make sense at all.
![the-fking-issue-0](https://user-images.githubusercontent.com/24369769/89078320-db848a00-d38c-11ea-9945-cf6ff5a0ce22.png)
![the-fking-issue](https://user-images.githubusercontent.com/24369769/89078289-c90a5080-d38c-11ea-9ba1-d74254d7a191.png)

Sorry if this is the wrong place to open this issue but I do not know which program causes this issue.
I use:

- nix
- home-manager
- cachix (I use this just for one package)

#### Technical details

 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.5.0, macOS 10.15.5`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.6`
 - channels(ihsan): `"home-manager, nixpkgs-20.09pre231837.2cd2e7267e5"`
 - channels(root): `"home-manager, nixpkgs-20.09pre228453.dcb64ea42e6"`
 - nixpkgs: `/Users/ihsan/.nix-defexpr/channels/nixpkgs`

**Comment by rycee** [comment]
This is not really related to Home Manager, it is more of a Nix and Nixpkgs issue. The "copying path" lines simply mean that those packages have changed since your latest update and are downloaded from the binary cache. This applies to packages that have been built by [Hydra](https://hydra.nixos.org/). Sometimes, in particular since you are tracking the unstable channel, Hydra hasn't had time to build all packages you depend on and Nix is then forced to build them locally.

It might be worth switching to the `nixpkgs-20.03-darwin` channel, which will not be updated as aggressively as the unstable one. I can't help much more than that since I've never used the Darwin platform. You can always ask in the #nixos @ freenode IRC channel for more advice w.r.t macos.

**Comment by ihsanturk** [comment]
Thank you so much. I will switch to the stable channel and see how it goes. Sorry to bothering this repo.

**Comment by rycee** [comment]
No worries, good luck.
