### ISSUE TITLE
i3: default keyconfig with configurable modkey

### ISSUE THREAD

**Issue by Moredread** [rycee/home-manager#147]
I think it might be useful to be able to specify the modkey for the keyconfig, without having to copy it over to my own config.

**Comment by uvNikita** [comment]
I agree that it would be nice to be able to change modkey without copying the whole default configuration.

The reason I didn't include modkey in the module parameters is that i3 doesn't treat it in any special way. The usage of mod key seems to be just a common pattern among i3 users. In particular, there is no specific name for this key, `$mod` is probably just the most used one. I also didn't want to add the parameter which would set i3 variables (`set $<name> <value>`) since nix itself can be used for that purpose.

Considering above, I'm not sure how to provide the way of setting modkey that would make sense in both default and custom configuration cases. Let me know if you have an idea of how this can be achieved.

**Comment by Moredread** [comment]
One idea would be to expose the default mapping as a function that is called with a modkey. I.e. the user could write 

```
xsession.windowManager.i3config.keybindings = xsession.windowManager.i3config.default_config "Mod4";
```

I'm not sure though how to implement a function in a module, that can be called outside of it, and am also not sure if a function can have a 'prefix' as above.

**Comment by manveru** [comment]
Made a PR that could solve this: https://github.com/rycee/home-manager/pull/222

**Comment by uvNikita** [comment]
After some discussion, we decided to add the modifier option to the i3 module as you proposed.
So if you will update to the current version of home-manager you should be able to set `xsession.windowManager.i3.config.modifier` setting to one of the possible modifier keys which will be automatically reflected in the default keybindings.

Note that you can also override or extend default set of keybindings using `lib.mkOptionDefault` function without copying everything to your config as well. Please, refer to the updated documentation for the example.

Thanks for creating the issue!
