### ISSUE TITLE
xmonad not in $PATH on restart

### ISSUE THREAD

**Issue by league** [rycee/home-manager#153]
Hi, I recently started using the `xsession.windowManager.xmonad` module instead of `windowManager.command`. One new issue I'm noticing is that if I try to manually restart xmonad with mod-q, it pops up an xmessage saying `xmonad not in $PATH: /home/league/bin:...etc...`.

Previously, I had my xmonad package in `home.packages`, which I guess would solve this. But I removed it since the module constructs the precise package spec, and I didn't want a differently-hashed one to creep in so that I'm hanging onto two of them.

I guess the solution would be either to:

 1. Add the `let`-bound `xmonad` package within the module to `home.packages`, maybe with an option to enable that or not.

 2. Or at least expose the constructed package, so it can be referenced and I can add it to `home.packages`. (meh?); or

 3. Hack the xmonad build itself so it doesn't rely on its own executable being in the `$PATH`?

Not sure what's the best way forward, but I could help troubleshoot and open a PR.

**Comment by league** [comment]
It suddenly occurred to me that maybe the goal here is that an xmonad restart should be triggered by home-manager itself in response to a change in the config, and there shouldn't be need to manually restart with mod-q…

**Comment by rycee** [comment]
Hi, thanks for the report :-)

Yeah, in principle it shouldn't be needed to restart xmonad manually since the configuration is compiled and xmonad restarted on HM switch:
https://github.com/rycee/home-manager/blob/7a5b9152e97b74e51fff0e5e3545bef1c59d6504/modules/services/window-managers/xmonad.nix#L92-L109
I can't say if this works perfectly reliably, though, since I change my configuration once per decade or so ;-)

In any case, I think it still would be nice if manual xmonad restart works so it's worth to look into this anyway.

**Comment by Infinisil** [comment]
Oh that is indeed worth changing, adding the xmonad package to `home.package` sounds reasonnable. I haven't noticed this not working since I manually included xmonad in my packages when writing the xmonad module.

**Comment by rycee** [comment]
Agreed, I think it is fair to put it in `home.packages`. Added a commit that does just that.

@league Please try it out and see if it resolves the issue 🙂

**Comment by league** [comment]
@rycee Works. :white_check_mark:
