### ISSUE TITLE
home-manager is not able to use X anymore?

### ISSUE THREAD

**Issue by suolrihm** [rycee/home-manager#17]
Somedays ago i made a clean install of NixOS and now it seems like i can't manage my xsession with home-manager anymore.
When trying to login (Slim) i got the "Failed to execute login command" message.
Using the configuration.nix works.

NixOS Version: Unstable (17.09pre109180.0d4431cfe9)

**Comment by rycee** [comment]
Ok, sounds unpleasant. I'll need a bit more information to find the cause. Could you create a [gist](https://gist.github.com/) with the output of `journalctl --user --since -1m` just after attempting to do the login? Hopefully it will contain some log line showing the command that failed.

The `services.xserver` section of your system `configuration.nix` and the `xsession` section of your home-manager configuration would also help.

**Comment by suolrihm** [comment]
Okay. After rewritting the home.nix file, everthing works perfectly fine again.
Thank you for the response!

**Comment by rycee** [comment]
I'm glad it worked out for you ☺
