### ISSUE TITLE
zsh HISTFILE, HISTSIZE not set?

### ISSUE THREAD

**Issue by krey** [rycee/home-manager#177]
I don't know if this is an issue with home-manager or something bigger than that, but I'm not able to set my `HISTSIZE` by doing
```nix
programs.zsh.history.size = 10000;
```
or
```nix
programs.zsh.profileExtra = "HISTSIZE=10000";
```
since it's overwritten by `/etc/zshrc`.

The post that prompted it on reddit: https://www.reddit.com/r/NixOS/comments/7pt34f/how_to_stop_etczshrc_from_overwriting_histfile/

**Comment by uvNikita** [comment]
I confirm that `programs.zsh.history.size` indeed doesn't change the `HISTSIZE` env variable when `oh-my-zsh` is enabled. 

The reason is that `$ZSH/oh-my-zsh.sh` is sourced after `.zshenv` file where we set this variable. `oh-my-sh` [sources](https://github.com/robbyrussell/oh-my-zsh/blob/c3b072eace1ce19a48e36c2ead5932ae2d2e06d9/oh-my-zsh.sh#L31) all `.zsh` config files in its lib folder, including [lib/history.zsh](https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/history.zsh). There `HISTSIZE` is set to `10000` unconditionally.

I'll create PR in oh-my-zsh to add condition similar to `HISTFILE`. In the meantime, quickfix would be to add `programs.zsh.initExtra = "HISTSIZE=10000";` to your config file since it adds lines after `oh-m-zsh.sh` sourcing.

**Comment by uvNikita** [comment]
Seems like this issue was already brought up in `oh-my-zsh`, but PR was reverted: https://github.com/robbyrussell/oh-my-zsh/pull/3359. I guess we will have to fix it on our side.

**Comment by krey** [comment]
Thanks for the speedy response, Nikita. I'm a little confused though, since I do not use `oh-my-zsh`.
Are you able to reproduce my issue in an environment without `oh-my-zsh`?

**Comment by uvNikita** [comment]
No, with `oh-my-zsh` disabled, HISTSIZE is set correctly for me.

Do you have `programs.zsh.enable = true` in your system configuration? If that's the case then, as you mentioned, and according to https://www-s.acm.illinois.edu/workshops/zsh/startup_files.html, `/etc/zshrc` will be read after `~/.zshenv` and it will result in the same issue.

So it seems that it works for me with oh-my-zsh disabled because I only have `users.users.myuser.shell = pkgs.zsh;` in the system configuration and therefore don't have the default `/etc/zshrc` at all.

The proposed patch should fix your case too, but I see that we should do the same for `SAVEHIST` and `HISTFILE` variables since they are also defined in [/etc/zshrc](https://github.com/NixOS/nixpkgs/blob/412ad9447a861a26eaf762c504a2ec827cfedf9f/nixos/modules/programs/zsh/zsh.nix#L153).

**Comment by krey** [comment]
Thank you for the explanation and the fast fix.
