### ISSUE TITLE
Contribution: How to?

### ISSUE THREAD

**Issue by Baughn** [rycee/home-manager#180]
CONTRIBUTING.md is fairly comprehensive, but it misses one important piece of information.

Once the repository has been cloned and edited, what's the right incantation to build/run home-manager using it?

**Comment by rycee** [comment]
Sorry for the above spamming! Thanks for the suggestion, you make a good point!

I made an attempt at explaining this so please have a look at https://github.com/rycee/home-manager/blob/expand-contributing/CONTRIBUTING.md#fork-and-create-a-pull-request and see if it is clear enough.

**Comment by Baughn** [comment]
Looks good.

Though... For the second option, wouldn't you need to run home-manager twice? Once to reconfigure it, then again to use the new repo? If so, then that bears mentioning.

It would also be useful to explain how to back out a bad state, in the event that you get any of this wrong.

**Comment by rycee** [comment]
Sorry for the delay. I've added some basic [rollback instructions](https://github.com/rycee/home-manager/blob/master/README.md#rollbacks) to the readme file since it's relevant for all users, not just people wanting to contribute.

Also the contribution file mentions that you need to run `home-manager switch` to activate the change.

**Comment by rycee** [comment]
I merged the branch to master.

@Baughn If you feel there still are things lacking then please feel free to reopen. Many thanks for suggesting this improvement to the documentation 👍

**Comment by Baughn** [comment]
No, I think this is fine. :+1: 

Now I need to code up the contributions I had in mind. :V
