### ISSUE TITLE
polybar: bspwm desktops not always visible

### ISSUE THREAD

**Issue by Tmplt** [rycee/home-manager#195]
Polybar appears to start whilst bspwm is sourcing `~/.config/bspwm/bspwmrc`, so bspwm desktops are not always defined when the bar appears, if the polybar config now uses the bspwm module. Starting polybar in `bspwmrc` is a workaround.

I suggest home-manager starts polybar after bspwm is done with its config file.

**Comment by rycee** [comment]
Unfortunately, due to some [troubles with session dbus in NixOS](https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-341860410), we can't start the window manager through systemd (and thereby be able to add a `Before` ordering dependency on bspwm w.r.t. polybar).

As a quick and dirty work-around maybe it is possible to add a delay at the start of your `services.polybar.script` option. I guess it would have to be inside a sub-shell. Maybe something weird like

```sh
{ sleep 1; polybar bar & } &
```

??

Maybe simply having bspwm start the polybar process is the best?

**Comment by Tmplt** [comment]
`script = "{ sleep 1; ${pkgs.polybar}/bin/polybar laptop & } &"` oddly doesn't work; the bar never starts. I might have missed something in the syntax, however.

But indeed, rather than a (although unlikely) race condition, it is a better idea to start the bar in `bspwmrc`.

**Comment by rycee** [comment]
Yeah :-/

Once we're able to run the window manager as a systemd unit we'll be in a much better position to control the order of service execution relative the window manager. So I think it is best for now to start the bars from `bspwmrc` but hopefully it won't stay that way ;-)

I'll close the issue for now since we can't really do much about it.
