### ISSUE TITLE
feature request: add MPD user service

### ISSUE THREAD

**Issue by throwup** [rycee/home-manager#203]
MPD (music player daemon) is probably a service that lots of people (including me) would like to run for specific users. In your blog you describe that managing user services is a big priority for home-manager, so I wanted to ask if you would be interested in implementing it (and maybe also modipy, if that's possible).

**Comment by ayyjayess** [comment]
@throwup - [this](https://gist.github.com/ayyjayess/b610231b623a140e2173f9a30fd1c291) module should work if you set `services.mpd.dataDir` to where your mpd data is.

@rycee - What is your opinion on importing the `<nixpkgs>` set and reusing the options provided in it? It could save on rewriting/copy+pasting options and keeping better compatibility with upstream.

**Comment by rycee** [comment]
@ayyjayess Unfortunately it is not entirely safe to import the options from `<nixpkgs>` although I entirely understand the motivation. The reason is that, if the module options change in Nixpkgs then the evaluation of the Home Manager modules may break.

That said, we have made [a few exceptions](https://github.com/rycee/home-manager/blob/f2265b10e4eb48c66d334fa1d90bebb4affbec69/modules/modules.nix#L75-L77) for some modules that are imported as-is into Home Manager. These modules are very central to the NixOS module system so I imagine them to be very stable. I'm not as certain about the mpd module, though, so I would be a bit reluctant about doing the same for the mpd options. Sadly.

**Comment by Infinisil** [comment]
@ayyjayess Unfortunately the `import <nixpkgs/nixos> {}` in your gist won't work for everybody, because it could fail trying to find a `configuration.nix` (for me because I'm using nixops, and probably for Darwin people too), so I think the options need to be duplicated unfortunately

**Comment by rembo10** [comment]
I created a pull request here: #311 
It probably needs work but it gets it going

**Comment by rycee** [comment]
I've merged the #311 module and am therefore closing this. Thanks @rembo10 for creating the module and @throwup for opening the issue! 🙂
