### ISSUE TITLE
polybar can't find i3

### ISSUE THREAD

**Issue by nico202** [rycee/home-manager#206]
Hi, the relevant part of my config is:

```nix
  services.polybar = {
    enable = true;
    package = pkgs.polybar.override {
      mpdSupport = true; mpd_clientlib = pkgs.mpd_clientlib;
      i3Support = true; i3 = pkgs.i3; jsoncpp = pkgs.jsoncpp;
    };
    script = ''polybar bar &'';
```

the generated systemd service is:
```conf
[Service]                                                                                                                                                                                         
Environment=PATH=/nix/store/1z2cnfmdx0z82jm2rbz790adin7640xk-polybar-3.1.0/bin                                                                                                                    
ExecStart=/nix/store/zkihhy9nsnqqy9ds4vdqnq8rpi3ylykw-polybar-start/bin/polybar-start   
```

manually running `polybar bar` works as expected, while calling

> PATH=/nix/store/1z2cnfmdx0z82jm2rbz790adin7640xk-polybar-3.1.0/bin /nix/store/zkihhy9nsnqqy9ds4vdqnq8rpi3ylykw-polybar-start/bin/polybar-start   

I get 

```
sh: i3: command not found
error: Disabling module "i3" (reason: Could not find socket: <empty>)
warn: Termination signal received, shutting down...
```

**Comment by nico202** [comment]
@uvNikita

**Comment by uvNikita** [comment]
Thanks for reporting the issue.

Looks like polybar  [uses](https://github.com/jaagr/polybar/blob/d8414c6ec547b58c9ec05db1db46509847f09380/src/modules/i3.cpp#L17) i3ipc to communicate with i3. Error appears since `i3ipc::get_socketpath` simply [calls](https://github.com/drmgc/i3ipcpp/blob/f4d143a3fa93518f5750dec51180f4af0f25be66/src/ipc.cpp#L256) i3 executable to get the socket path.

One workaround for this is to append i3 package bin folder to `$PATH` in starting script:
```
  script = "PATH=$PATH:${pkgs.i3}/bin polybar bar &"
```

It would be nice to fix it for all users, but I'm not sure how we can do that.

**Comment by rycee** [comment]
Hmm, I wonder if not the Nixpkgs polybar package should patch this `popen` in its `lib/i3ipcpp/src/ipc.cpp` to have the full path to the i3 binary. Seems like an impurity otherwise.

**Comment by rycee** [comment]
Btw, good find @uvNikita! 👍

**Comment by uvNikita** [comment]
@rycee I think you are right, it should be patched in nixpkgs.

**Comment by uvNikita** [comment]
Thanks to @ayyjayess the fix is in the master branch of nixpkgs, so if you are using the unstable channel, adding i3 binary to the PATH should not be necessary anymore.
