### ISSUE TITLE
minimal-module list (rfc0022)

### ISSUE THREAD

**Issue by Mic92** [rycee/home-manager#220]
Does home-manager has the same problem as NixOS?
https://github.com/NixOS/rfcs/pull/22
Would it be easier to fix in the current state?

**Comment by rycee** [comment]
@Mic92 Yes, Home Manager has a similar problem since we have a [modules.nix](https://github.com/rycee/home-manager/blob/master/modules/modules.nix) file which imports everything. It's not nearly as problematic as in NixOS, though, since we have much fewer modules.

But yeah, something like lazily loading modules would be sweet and if a solution is found for NixOS it would be great if it was general enough to also apply for Home Manager :-)

**Comment by rycee** [comment]
I'll close this with the same motivation as in the NixOS issue, i.e., that flakes will solve everything 🙂

**Comment by Mic92** [comment]
I don't see how flasks would solve the problem with in-tree modules in both projects.

**Comment by leotaku** [comment]
@Mic92 flake would allow for relative imports within NixOS/home-manager. This means instead of having to auto-import every module the user/developer can easily manually import the modules they want to use.

> I expect that evaluation time gets even worse since it encourages to have multiple nixpkgs versions.

That would never happen within Nixpkgs/home-manager. External dependencies currently use "hacky" methods so the standardized Flakes should make them faster too.

**Comment by Mic92** [comment]
> @Mic92 flake would allow for relative imports within NixOS/home-manager. This means instead of having to auto-import every module the user/developer can easily manually import the modules they want to use.
> 
> > I expect that evaluation time gets even worse since it encourages to have multiple nixpkgs versions.
> 
> That would never happen within Nixpkgs/home-manager. External dependencies currently use "hacky" IFD methods so the standardized Flakes should make them faster too.

I don't see how the flake interface speeds-up evaluation over import-from-derivation. In the end still the same amount of code needs to be executed.
Every flake has a `flake.lock` pinning nixpkgs: https://github.com/edolstra/dwarffs/blob/master/flake.lock#L7
This means if I use a flake, I have to use its nixpkgs version. If I use 5 flakes I could easily end up with 5 different nixpkgs versions which not only makes evaluation slower but also mean that my system ends up with slightly different library versions. This feels a bit like the docker ecosystem - I don't want to use out-dated libraries from an old nixpkgs revision just because the flake never has been updated.

**Comment by leotaku** [comment]
@Mic92 
> I don't see how the flake interface speeds-up evaluation over import-from-derivation. In the end still the same amount of code needs to be executed.

You are probably right. I was thinking along the lines that if multiple `flake.lock` pinned the same dependencies that could help speed up imports and evaluation. This likely isn’t' the case though as nix should already memoize these calls. Sorry.

> This means if I use a flake, I have to use its nixpkgs version. If I use 5 flakes I could easily end up with 5 different nixpkgs versions which not only makes evaluation slower but also mean that my system ends up with slightly different library versions.

But how else could you possible hope to ensure that the flakes you use are compatible with your system? E.g. one of your imported flakes needs to use a different GHC version? One of the main selling points of nix is that it allows you to have different versions of the same software installed at the same time.

Also in the current MVP it is specified that nix will only respect the topmost `flake.lock` (which I suppose is generated from the Lockfiles of all of its dependencies). So I am sure you will be able to manually override the `nixpkgs` versions of your dependencies. (Unlike with some current solutions)
