### ISSUE TITLE
Does home-manager only support options for programs in this repo?

### ISSUE THREAD

**Issue by MichaelBergquistSuarez** [rycee/home-manager#239]
Hi, sorry if this is a stupid question (new to nix and nixos);

I've read the README and https://rycee.net/posts/2017-07-02-manage-your-home-with-nix.html but I can't seem to understand how to implement configuration for programs that are not modules in this repository.

For example, I would like to make some user environment changes to `tmux`. I took a look at https://nixos.org/nixos/options.html#tmux and figured I could enter this in my `configuration.nix` using the [home-manager module](https://github.com/rycee/home-manager/blob/master/modules/misc/news.nix#L507)

```nix
{
  home-manager.users = {
    michael = {
      programs = {
        tmux = {
          # Configurations mentioned in https://nixos.org/nixos/options.html#tmux here
        };
      };
    };
  };
}
``` 

This gives me:
```
error: The option `home-manager.users.michael.programs.tmux' defined in `/etc/nixos/config/users-and-groups.nix' does not exist.
``` 

What do I need to do in order to apply these configurations?

**Comment by MichaelBergquistSuarez** [comment]
Dammit, of course I managed to figure it out shortly after posting this issue. Sorry, my bad.

For future reference I simply did:
```nix
{
  home-manager.users = {
    michael = {
      home.file.".tmux.conf".source = ./tmux.conf; # Can't be ./.tmux.conf for some reason
    };
  };
}
``` 
And created the file `tmux.conf` in the same directory. Works like a charm. 

It would be cool if it also was possible to use the options available at https://nixos.org/nixos/options.html#tmux somehow

**Comment by rycee** [comment]
Yeah, like you noticed Home Manager configurations cannot include options that are defined in NixOS. This is because they are having some different underlying systems and assumptions.

I know this is a bit unsatisfying and I hope this situation can be improved in the future.

In general it is fairly easy to port "user focused" modules from NixOS to Home Manager and I expect tmux would fit this category it just that nobody has had the inclination to actually do this porting.

In any case, thanks for trying out Home Manager and being willing to report problems :-)

**Comment by MichaelBergquistSuarez** [comment]
Yeah, I love it. This is what nixos has been missing, it pretty much completes it. When I get a better grasp on nix I would love to try to contribute. 

I guess `nixuser` that you've mentioned (and from my understanding have done some work in) may be merged one day. Do you think `nixuser` would replace `home-manager` in your own machine, or would `home-manager` still be relevant?
