### ISSUE TITLE
Override mkmerge configuration

### ISSUE THREAD

**Issue by LightDiscord** [rycee/home-manager#256]
I was wondering if there was a way to define parameters that are not erased by the merge of a configuration.

### Example

In [dunst.nix](https://github.com/rycee/home-manager/blob/e055e4a092e0920cc2f8dc7f6b665bf6dbba6a4b/modules/services/dunst.nix#L139-L152) I need to override service environment so I would like to make something like below.

```nix
{ pkgs, ... }:

{
    services.dunst.enable = true;

    systemd.user.services.dunst.Service.Environment = "GDK_PIXBUF_MODULE_FILE=${pkgs.librsvg}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache";
}
```

But when I run the command `systemctl --user cat dunst.service` the Environment line isn't here.`

Is there any other way than to create another service or copy the `dunst.nix` file to add our line.

**Comment by rycee** [comment]
Unfortunately the `systemd.user.services` option doesn't do merges very well because it is using a much more primitive setup than NixOS does. So right now it is necessary to replace a whole service definition rather than setting a specific field. I know this is not very satisfying and hope to change it at some point.

Fortunately I think the problem you are trying to resolve here is better solved in the dunst package. I made the referenced PR to fix this. If you can then please apply the PR to your setup to verify that it actually fixes the problem.

**Comment by LightDiscord** [comment]
Good morning,

Your patch works perfectly, but I found a very strange behavior, the dunst to display notifications is not the same as using by the service.

The one used is the one in the `home.packages`. Even stranger, I was able to remove the service and keep the dunst from the `home.packages` and it still works.

**Comment by rycee** [comment]
Unfortunately this is because the session dbus is a bit broken in NixOS. See https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-341860410 for an in-depth explanation. The gist of it is that the dunst systemd service is not actually used when running under NixOS. To restart the dunst process it is best to just kill it and dbus will later start a new process when something wants to send a notification.

**Comment by rycee** [comment]
The dunst in the NixOS stable channel now has the fix.

Also @nonsequitur fixed the systemd Home Manager module to allow recursive updates so your

```
systemd.user.services.dunst.Service.Environment = "GDK_PIXBUF_MODULE_FILE=${pkgs.librsvg}/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache";
```

line should now work (but you shouldn't need it anymore).

So I'll close the issue. If there was anything I missed then feel free to reopen :-)
