### ISSUE TITLE
i3 startup applications with assigned workspaces rarely work and should be depreciated

### ISSUE THREAD

**Issue by Ameliorate** [rycee/home-manager#265]
https://rycee.github.io/home-manager/options.html#opt-xsession.windowManager.i3.config.startup._.workspace

This option will output in the i3 config as 
```
exec --no-startup-id i3-msg 'workspace ${workspace}; exec ${command}'
```
This is incorrect, because the command opening the window might fork and open the window several seconds later, and i3 has no ability to keep track of that. So instead it will switch through all the workspaces, then will open all the windows on the last workspace stated. That would cause the `workspace` option to act buggy and be very difficult to debug.

At least that is what should be happening. Instead, i3 is exhibiting some sort of strange "grouping" behavor where it will instead open the window on the first workspace stated. Even if `i3-msg 'workspace n; exec ...` is ran seconds after the first invocation, windows will still be placed on the same workspace.

Even if that wierd behavor weren't present, using the pattern that is written to the i3 config is incorrect, and is stated as wrong in multiple places online[1]. Instead [layout-saving](https://i3wm.org/docs/layout-saving.html) or for_window should be used, however it is impossible to get enough info for these options from just the command.

Thus, I think the `xsession.windowManager.i3.config.startup.*.workspace` option should be depreciated in favor of other options. It is impossible to create this option without also taking additional information, such as the window class or title.

1. https://www.reddit.com/r/i3wm/comments/33c6qu/open_multiple_applications_at_startup_on/cqki4ok/  
https://unix.stackexchange.com/questions/96798/i3wm-start-applications-on-specific-workspaces-when-i3-starts
https://unix.stackexchange.com/questions/134980/how-do-you-implement-layout-with-the-autostarting-of-applications-in-the-i3-wind?noredirect=1&lq=1

**Comment by rycee** [comment]
@Ameliorate Thanks for the very detailed report! I personally don't know much about i3 so I cannot comment very much.

@uvNikita, would you mind having a look at this when you have some time to spare?

**Comment by uvNikita** [comment]
@Ameliorate Thanks for creating an issue and for a detailed description.

You are right that the current implementation is not correct, it worked in my case only because I had one command with workspace specified and others assigned based on their classes. As you mentioned, it doesn't look like there a way to implement this option as intended without using big hacks. Therefore, I agree that we should add a comment in documentation and deprecate this option.

That said, it would be very nice to integrate i3 layout-saving capabilities into the module. Can't promise that I will have time for that in the nearest future though :)

**Comment by palewire** [comment]
I encountered this same bug.
