### ISSUE TITLE
forward arguments to nix-build ?

### ISSUE THREAD

**Issue by teto** [rycee/home-manager#312]
Wanted to work on home-manager while on the train so I fetched packages beforehand but then I got
```
home-manager --no-substitute switch                                                                                                                               ~
/home/teto/.nix-profile/bin/home-manager: illegal option -- -
/home/teto/.nix-profile/bin/home-manager: line 342: OPTARG: unbound variable
```
I've looked at home-manager and seems like it forwards argument to  nix-build except for this case where optarg fails before.

**Comment by rycee** [comment]
Unfortunately the home-manager tool uses the Bash `getopt` builtin command. So it can't cope with long options. And the `getopt` tool, which can handle long options is in the util-linux package so it is limited to Linux platforms.

I might simply redo the option parsing completely in the tool so that it is done directly in the code, shouldn't be too much harder but will be much more flexible to handle, for example, your case.

Thanks for the report! I'll try to have a look at fixing the issue as soon as possible. I'm having a bit of vacation now, though, so please be patient 🙂

**Comment by rycee** [comment]
I fixed the option parsing a while back but forgot about this issue. Added `--(no-)substitute` support now.
