### ISSUE TITLE
Systemd services don't update

### ISSUE THREAD

**Issue by jD91mZM2** [rycee/home-manager#355]
Any changes to an existing systemd service (systemd.user.services) don't update. Only new services are created, old are never deleted.

Sorry if this is a duplicate or already solved, I tried searching but don't know the right terms to search for so I couldn't find anything.
Using the 18.03 release.

**Comment by jD91mZM2** [comment]
Oh, actual problem seems to be that `systemctl --user daemon-reload` isn't ran.

Relevant:
```
Activating reloadSystemD
User systemd daemon not running. Skipping reload.
```

**Comment by danbst** [comment]
got this as well. User services isn't restarted after a change.

**Comment by Shados** [comment]
@rycee ...instead of making it smarter, maybe make it dumber -- always reload, and just log failures? Is there some non-obvious reason you want to avoid attempting a `daemon-reload` if the systemd user session isn't running?

**Comment by leotaku** [comment]
I agree with @Shados. @rycee could you explain what the code intends to achieve?

**Comment by rycee** [comment]
These parts of Home Manager are quite old and are not very well made, I would like to completely rewrite them at some point. The second issue is that the user dbus session is quite brittle under NixOS and this is what I'm trying to improve right now.

**Comment by pstch** [comment]
Note to other users: this problem can be avoided by setting `systemd.user.startServices` to `true`.

**Comment by Shados** [comment]
@pstch that is not the case. If you take a look at the code below, the `startServices` check is only relevant *after* the check that is failing here:
https://github.com/rycee/home-manager/blob/7159c293af3362370159da45fdb1ac0b0b7c373c/modules/systemd.nix#L245-L251

**Comment by pstch** [comment]
@Shados yes that is true, but `startServices` can still help for this problem in some cases, as it prevents the system from becoming degraded because of old services that were never deleted.

The issue text contains "Only new services are created, old are never deleted.", which can be fixed by using `startServices`, unless the system is already degraged. Sorry for not being clear enough.

A way to bypass the skipped reload problem is to run "systemctl --user reset-failed" before calling "home-manager switch", but it comes with its own drawbacks (losing failed states for services that would not have been restarted by home-manager).
