### ISSUE TITLE
Home-manager does not create .profile anymore?

### ISSUE THREAD

**Issue by turion** [rycee/home-manager#381]
I have this as part of my config:

```
  home = {
    sessionVariables = {
      EDITOR = "vim";
      LOCALE = "de_DE.UTF8";
    };
  };
```

But no `.profile` file or similar is created and correspondingly these variables aren't set.

**Comment by turion** [comment]
I thought that home-manager would create `.profile`, and it did on other installations, but apparently not anymore??

**Comment by rycee** [comment]
Hi @turion. No Home Manager will not produce a `~/.profile` file unless you explicitly set `programs.bash.enable = true`. This is because a user may very well want to manage their own Bash installation, in which case they are expected to put
```bash
. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
```
in their `~/.profile` to make sure the Home Manager session variables will be set.

**Comment by turion** [comment]
Thanks, of course!
