### ISSUE TITLE
No way to change X sessions once home-manager enables them? 

### ISSUE THREAD

**Issue by JonathanReeve** [rycee/home-manager#391]
As [the README](https://github.com/rycee/home-manager#graphical-services) says, in order to let home-manager handle certain services, like dunst, it first has to handle the X session. But as far as I can tell, letting home-manager handle the X session takes over every possible X session. I use SDDM as a display manager, and have two sessions set up that I can choose from at login: a minimalist one, using BSPWM, which home-manager launches with `xsession.windowManager.command`, and one with KDE Plasma, which NixOS handles, with `services.xserver.desktopManager.plasma5.enable = true;`. The trouble is, if home-manager manages the X session, logging in to *either* the BSPWM session or the Plasma session (selecting these options in SDDM) will launch BSPWM, regardless. But I'd still like to be able to log into Plasma every so often. Is there a way to accomplish that?

**Comment by rycee** [comment]
Yeah, this is because NixOS (I don't know about other distros) unconditionally uses `~/.xsession` when it is present. I would have preferred if it had been treated as another desktop manager type thing and selectable in the display manager. So I would consider this a bug, or at least a weakness, in NixOS.

In any case it may be possible to do a work-around. I created a branch called [`xsession/session-script-path`](https://github.com/rycee/home-manager/pull/392) that adds a Home Manager option `xsession.scriptPath`. If you try this branch and add

```nix
xsession.scriptPath = ".xsession-hm";
```

to your Home Manager configuration and

```nix
services.xserver.desktopManager.session = [{
  name = "home-manager";
  start = ''
    ${pkgs.stdenv.shell} $HOME/.xsession-hm &
    waitPID=$!
  '';
}];
```
to your system configuration then it should be possible to select "home-manager" as a session in your display manager.

Please consider this as an experiment 😉

**Comment by JonathanReeve** [comment]
Great! Works a charm. Thanks. Why not merge this into master? I can't imagine it'd interfere with anything. Might need to add the system configuration snippet, though, to the description.

**Comment by rycee** [comment]
Yeah, I just wanted to verify that it works as expected before putting it in master.
