### ISSUE TITLE
The 'systemd.user' interface doesn't match NixOS's

### ISSUE THREAD

**Issue by alunduil** [rycee/home-manager#418]
The interface for configuring systemd user units being different from NixOS's and not documented well in the home-manager manual leads to a less than ideal user experience.  It'd be preferable to keep common components like this similar to the NixOS configuration but I'm probably missing a good reason to keep it separate like it is.

So this comes down to two obvious resolutions:

1. make the home-manager interface match NixOS's
2. document the home-manager interface to make managing systemd user units easier

Let me know if this isn't clear or if I need to provide examples.

**Comment by rycee** [comment]
Yeah, your observation is absolutely correct. This is a problem known since the inception of Home Manager and I can promise that I made several valiant attempts to use the systemd module from NixOS 🙂

Unfortunately it was too much of an undertaking for me and would most likely require a number of changes on the Nixpkgs side. To copy it over to the HM repo and adapt it there would make the maintenance job too large, I believe. So for now I'm prefering the worse is better solution.

To improve the documentation sounds like the most likely in the short term and I'm hoping to focus more on the manual in the future since there now is infrastructure to build and publish it automatically on gitlab.

**Comment by alunduil** [comment]
That sounds awesome.  I'll see if I can submit a draft of changes to the documentation so you have something to build on.
