### ISSUE TITLE
What files are touched by home-manager?

### ISSUE THREAD

**Issue by memberbetty** [rycee/home-manager#503]
Using home-manager is not possible for me currently, because it is not clear to me what is going to happen when I enable it. I have an existing .bashrc, .bash_profile, .profile and similar for zsh. 

I do not want these files to be overwritten, but if I know which ones are being used by home-manager, I could consider porting them. 

Please document what the tool does more precisely.

**Comment by Amarandus** [comment]
As documented [in the README.md](https://github.com/rycee/home-manager#keeping-your--safe-from-harm), it should be save to activate even with existing dotfiles.

When configuring your userspace with home-manager, the configurations will be added to the nix-store and symlinked into your `~`.

By the way, if you worry about your dotfiles, I'd recommend doing a backup - this is unrelated to home-manager, but a backup might save you from other harm than a configuration mistake, too.

**Comment by rycee** [comment]
@memberbetty Yes, as @Amarandus said. Home Manager shouldn't overwrite an existing file, if it detects one then it will stop the switch before changing anything in the home directory.

If you manually want to check the files generated by Home Manager before switching then you can run `home-manager build` instead of `home-manager switch`. This will generate a symlink called `result` in the current directory, this links to the generated Home Manager generation. Run
```command
$ find result/home-files/
```
to see all files that will be linked into your home directory.

**Comment by memberbetty** [comment]
Please consider creating a link from the installation section to the "Keeping your ~ safe from harm" section.

**Comment by Jomik** [comment]
I'd suggest simply reading all of the README.. There is a usage section which is quite relevant as well, and would let you know what files would be touched intuitively. The `Keeping your ~ safe from harm` section simply mentions that home-manager will not override files unless it is already managed by home-manager.

**Comment by rycee** [comment]
I'm inclined to leave the readme as is. If the wording can be made clearer then I'd be happy to accept a PR.
