### ISSUE TITLE
Feature request: Merge nixos-module-user-pkgs

### ISSUE THREAD

**Issue by maralorn** [rycee/home-manager#549]
I would be interested in what is missing to merge the nixos-module-user-pkgs into master. I don't see any technical reason.
It does not feel so nice to lag a bit behind master and sometimes following a constantly rebased branched is quite inconvenient. (e.g. when you want to try an earlier version).

**Comment by rycee** [comment]
I recall some issue with Qt applications, and I mention this in https://github.com/rycee/home-manager/pull/97#issuecomment-362791304 but I can't remember exactly what the issue was.

I would very much like to merge this branch, nobody likes having it around for so long and rebasing it regularly. I don't use it myself, though and simply don't have the time to thoroughly use it to be confident it won't break too many things.

It might be possible to change the behavior such that it will use `users.users.<name?>.packages` only if you have HM state version 19.03 or later. That is probably a more robust way forward since it would allow people to try it out without too much risk.

**Comment by rycee** [comment]
@kalbasit Yeah, that's sort of what I meant by restricting it to state version 19.03 or later. So for people having the state version set to 18.09 it would keep installing to `~/.nix-profile`.

**Comment by kalbasit** [comment]
@rycee Let's do that then, I would love to try it out on my daily driver as opposed to dedicate time for testing it.

**Comment by rycee** [comment]
I've started working on this and it should be quite doable. I could give you a deadline for when it's ready but then I'd also have to tell you that I most likely would break the deadline 😉

**Comment by rycee** [comment]
See #580 for a PR that supports both `~/.nix-profile` and `/etc/profiles` installation. You need to add
```
home-manager.useUserPackages = true;
```
to your NixOS configuration to enable installation into `/etc/profiles`. I've tested this a bit locally but not super extensively so don't move to this branch when you have important other work to do 🙂

**Comment by kalbasit** [comment]
@rycee you're awesome, thank you! I'll try it on the way to work tomorrow!

**Comment by maralorn** [comment]
I just went ahead and deployed this on my productive system. Seems to work for me.

I am just a bit curious, why we need the boolean flag. Does anyone have the `home-manager/nixos` module included in their system `configuration.nix` without using the `/etc/profiles` installation?

I am not against that option it makes sense to have it. With it it would it even be possible to merge this into nixpkgs. But I don't understand why not having this option would break anyone's setup when merging into master. It is my understanding that the features in this branch shouldn't affect users installing via `home-manager switch` at all.

**Comment by rycee** [comment]
@kalbasit Glad you like it, hope it works well for you!

@maralorn Good to head that it worked! I wanted the boolean flag because I don't entirely trust the `/etc/profiles` installs, for example, I had issues with Qt programs when I tried it. Also I imagine some users have scripts and such that include references into `~/.nix-profile` and I want to avoid breaking that if possible.

**Comment by rycee** [comment]
In master now 😀
