### ISSUE TITLE
Git breaks with bad config file

### ISSUE THREAD

**Issue by c0deaddict** [rycee/home-manager#557]
After commit https://github.com/rycee/home-manager/commit/a68c8cf5f1567faf02631c6d815daad2166bf26b my git command breaks with the error:

```fatal: bad config line 28 in file /home/jos/.config/git/config```

The generated config file looks like this:

```ini
[alias]
br=branch
ci=commit
co=checkout
d=diff -w
dump=cat-file -p
st=status
type=cat-file -t

[commit]
gpgSign=true

[filter "lfs"]
clean=git-lfs clean -- %f
process=git-lfs filter-process
required=true
smudge=git-lfs smudge -- %f

[gpg]
program=/nix/store/26vy8n395dn2jc6mnfvbacqy7brqjjjh-gnupg-2.2.12/bin/gpg2

[merge]
tool=/nix/store/g3c8f397z4mr3gn9km1hh9yks2iz01n9-meld-3.20.0/bin/meld

[push]
default=current

[sendemail.josvanbakel@gmail.com]
from=josvanbakel@gmail.com
smtpEncryption=tls
smtpServer=smtp.gmail.com
smtpServerPort=465
smtpUser=josvanbakel@gmail.com

... more email identities ...
```

Line 28 is the line starting with `[sendemail...`. Looking for documentation about the gitconfig I can't find any mention of configuring multiple `sendemail` identities. For now i've reverted to the commit before this change.

**Comment by aheaume** [comment]
Hello!

I was just opening an issue for this as well. The new feature in #547 looks interesting, however I may have found a bug.

This is the relevant `home.nix` section

```
accounts.email = {
   # ...
   accounts = {
     "whatever@gmail.com" = {
       primary = true;
       flavor = "gmail.com";
       address = "whatever@gmail.com";
       userName = "whatever@gmail.com";
       realName = "aheaume";
       notmuch.enable = true;
     };
     # ... more accounts
   };
};
```

Since the update, home-manager adds these blocks in my gitconfig file:

```
[sendemail.whatever@gmail.com] # this is line 66
from=whatever@gmail.com
smtpEncryption=tls
smtpServer=smtp.gmail.com
smtpServerPort=465
smtpUser=whatever@gmail.com
```

which makes git barf with

`fatal: bad config line 66 in file /home/aheaume/.config/git/config`

This is how far as I can debug right now. I disabled `accounts` entirely since I could not find any way to disable #547 from a quick look at the code. Is this something I need to fix in my config? How may I assist in solving the issue?

Have a nice day :)
Alex

**Comment by rycee** [comment]
Sorry for the inconvenience. I've changed the module to allow a wider range of characters in the account identifier.

Please give it a try now.

**Comment by aheaume** [comment]
LGTM, thank you!

**Comment by wirew0rm** [comment]
I have a similar problem with a backslash in the username which gets written unescaped into the git config.

**Comment by rycee** [comment]
@wirew0rm Backslash in the username? Ouch. Could you open a new issue with an example and how it should look with correct escaping?
