### ISSUE TITLE
Automatic sidelining of existing files

### ISSUE THREAD

**Issue by nyarly** [rycee/home-manager#585]
How irritating would it be to add a configuration to automatically move existing files to a `.bak` extension rather than making the user do that?

As I'm switching my not-trivial dotfiles to home-manager, the somewhat mechanical process of this rename is getting to me a little.

A further feature would be a "cleanup" command to find those files and remove them.

**Comment by rycee** [comment]
In principle this should not be very difficult, basically to copy the code currently used to check for collisions but moving the file instead of failing the activation. See
https://github.com/rycee/home-manager/blob/b8b391ad18b2ec47d1e95e247301edd4e8326154/modules/files.nix#L50-L83
The new code would have to run after `writeBoundary` and before `linkGeneration`.

One would also have to be smart about moving the file in case there already is a `.bak` file.

I'm unlikely to personally work on this but would be willing to review and merge a good solution.
