### ISSUE TITLE
programs.firefox.enableIcedTea does not do anything

### ISSUE THREAD

**Issue by Enteee** [rycee/home-manager#666]
I would like to install IcedTea Web for Firefox, hence I have, something like this in my user home configuration:

```
  programs = { 

    firefox = { 
      enable = true;
      enableIcedTea = true;
    }; 
```

but when I then build a vm (`nixos-rebuild build-vm && result/bin/run*)` firefox does not have that plug-in installed.

Is this expected?

**Comment by rycee** [comment]
Hmm, from what I can tell Firefox no longer supports plugins (except possibly Flash).

You could try adding

    programs.firefox.package = pkgs.firefox-esr-52-unwrapped;

to your configuration since that might be the last version that still allows non-Flash plugins. Afterwards you'll have to go to `about:config` and add a new Boolean option named `plugin.load_flash_only` and set it to false. See https://fedoramagazine.org/firefox-npapi-plugins-fedora/

**Comment by rycee** [comment]
I'll close this for now. Please reopen if you think there is more to be done about this inside Home Manager.

**Comment by Enteee** [comment]
Ok I understand that plugin support was dropped. But should the `enableIcedTea`-option then not also be removed?

**Comment by rycee** [comment]
The old LTS version of Firefox still seems to be in Nixpkgs. So in principle it can still be used. But I agree it is misleading. I will add a commit to mark the `enableIcedTea` as deprecated and explain it is only useful with the old LTS version.

**Comment by Enteee** [comment]
Ok thank you. I think making this deprecated is the right step. :+1:
