### ISSUE TITLE
getting pdftools/epdfinfo to work with emacs

### ISSUE THREAD

**Issue by matthuszagh** [rycee/home-manager#750]
Hello, i'm unable to get the epdfinfo server to work when installing pdf-tools with emacs. I'm currently setting pdf-tools in `programs.emacs.extraPackages` and although pdf-tools installs, the epdfinfo program is not built. Looking at the [nixpkgs source code](https://github.com/NixOS/nixpkgs/blob/e111f2323358e0aec9274b3f7a4fb3ded620d962/pkgs/top-level/emacs-packages.nix#L74), it seems like the build there is correct. However i'm not sure how to use this recipe with home-manager. I don't think it's using this recipe because i don't see the same build inputs and other configuration options in the pdf-tools derivation. Is it possible to use this with home-manager? Forgive me if this is obvious, i'm just a few days into nix...

**Comment by rycee** [comment]
I think this is an issue more suited for Nixpkgs since Home Manager doesn't do anything special with Emacs packages, it just directly uses the Nixpkgs infrastructure.

I've previously seen people having difficulties with pdf-tools, for example https://github.com/NixOS/nixpkgs/issues/33296, but since I don't use it myself I don't know any details.

**Comment by matthuszagh** [comment]
Ok I'll check over there. Thanks for the response!
