### ISSUE TITLE
enableBashIntegration (and friends) are redundant

### ISSUE THREAD

**Issue by peterhoeg** [rycee/home-manager#802]
Various bits of software support integration into various shells (bash, zsh and fish for some) but each integration point is guarded by an option such as ```programs.keychain.enableBashIntegration```.

Considering that all they do is inject a few lines into ```programs.bash.extraInit``` for the various shells, it seem completely superfluous to have the option in the first place as those ```extraInit``` bits only do something if the relevant ```programs.bash.enabled``` is ```true``` anyway.

The only argument for having the various options is to have some of the programs only integrated into one shell.

**Comment by rycee** [comment]
Yeah, these options are intended to be of use only for people who have, e.g., Bash enabled but don't want keychain enabled in Bash. I expect this is useful only for very few persons but figure the options are good to have since accomplishing the same thing would be difficult without them.

Do the options cause any particular problem other than spamming the documentation? If it's the documentation issue that is the main concern, then the options could be given `visible = false`.

**Comment by peterhoeg** [comment]
> Do the options cause any particular problem other than spamming the documentation?

I *just* realized that they all default to true. I had been setting them manually which was a pain. Yeah, then it really isn't a problem.... Sorry about the noise.

**Comment by rycee** [comment]
Ah! 😀

Yeah, I imagine very few people would need to override the default of these options.
