### ISSUE TITLE
blueman-applet: exception on startup

### ISSUE THREAD

**Issue by dermetfan** [rycee/home-manager#84]
`❯ systemctl --user start blueman-applet`

![2017-10-01t16 04 17 035392536 02 00](https://user-images.githubusercontent.com/4956158/31055384-4f7d0ff4-a6c2-11e7-859f-45c336987b2b.png)

I have not yet found any functionality that actually does not work after clicking OK though.

**Comment by rycee** [comment]
I'm not using Bluetooth but this seems to me like an issue that has to be resolved outside Home Manager. Basically, from what I can see the `org.blueman.Mechanism` D-Bus service is provided by the blueman package in Nixpkgs:

```console
rycee@beta:~/devel/nixpkgs$ nix-build -A blueman
/nix/store/8abl7bvx83g7ql4ri8qzkyjs3fyp3nss-blueman-2.0.4
rycee@beta:~/devel/nixpkgs$ cat result/share/dbus-1/system-service/org.blueman.Mechanism.service
[D-BUS Service]
Name=org.blueman.Mechanism
Exec=/nix/store/8abl7bvx83g7ql4ri8qzkyjs3fyp3nss-blueman-2.0.4/libexec/blueman-mechanism
User=root
rycee@beta:~/devel/nixpkgs$
```

The issue seems to be that this is a system service so it can't set it up for a single user. Ideally, I guess there should be a NixOS module for blueman (e.g., `services.blueman.enable = true`) but you could try installing blueman using `environment.systemPackages` in your system configuration. If it is installed system wide I suspect that the system dbus daemon will be able to find it…

**Comment by uvNikita** [comment]
@rycee is right, the problem seems to be connected that dbus can't find the blueman package.
To make it work I've added blueman to `services.dbus.packages` in my system configuration file:
```
services.dbus.packages = with pkgs; [ blueman ];
```

**Comment by dermetfan** [comment]
That solved the issue and I learned something about D-Bus. Thanks!

**Comment by CMCDragonkai** [comment]
Do you need both `environment.systemPackages` and `services.dbus.packages` at the same time specifying `blueman`?

**Comment by uvNikita** [comment]
@CMCDragonkai it should be enough with only `services.dbus.packages = [ pkgs.blueman ];` set.
