### ISSUE TITLE
Emacs package doesn't update when changing rev, only rev+hash change

### ISSUE THREAD

**Issue by codygman** [rycee/home-manager#872]
When changing rev to a newer revision in  something like this:

```
 src = fetchFromGitHub {
    owner = "emacs-mirror";
    repo = "emacs";
    rev = "oldrev";
    sha256 = "oldrevhash";
  }
```

No new rebuild is triggered if I only make this change:

```
 src = fetchFromGitHub {
    owner = "emacs-mirror";
    repo = "emacs";
    rev = "newrev";
    sha256 = "oldrevhash";
  }
```

I was expecting it to say "hash mismatch" or something, but I guess I can see why that wouldn't happen.

I ended up having to change the hash to a bogus value. I suppose I could have looked it up, but I'm not sure this behavior is what we want either.

**Comment by shanesveller** [comment]
I don't think this has anything to do with `home-manager` in particular, this is just Nix's own natural behavior for how packages are recognized as essentially-different or not. If you need a simple way to force a new package build, you could change the package's `version` (outside of this `src`) to use a simple timestamp whenever you change the `src` definition, i.e. `20191017` with an optional suffix.

**Comment by rycee** [comment]
Sorry about the dely 🙂

Indeed this has nothing to do with HM and is expected Nix behavior. Since the hash was kept as-is Nix was able to find the old entry in the Nix store and therefore did not fetch the source again. It is extremely unlikely that this behavior is going to change so the suggestion is to use one of the `nix-prefetch` tools or use the bogus hash trick.
