### ISSUE TITLE
vscode extensions no longer work on macos

### ISSUE THREAD

**Issue by pradyuman** [rycee/home-manager#888]
After https://github.com/rycee/home-manager/pull/795 was merged, vscode extensions no longer work on macos. It seems like the extensionPath is correct (`.vscode/extensions`) so I'm not sure why this doesn't work. I'm happy to help debug but I'm not very familiar with nix debugging tools.

**Comment by rycee** [comment]
@pradyuman Do you get any error message or similar?

@pasqui23 Any idea what could cause problems on macOS?

**Comment by pradyuman** [comment]
No error message, but the vscode extensions don't exist when I launch the editor. When I run `nix-collect-garbage -d`, the extensions are deleted, so I'm thinking there's some issue with the way they are being linked.

**Comment by AmandaCameron** [comment]
The issue with this appears to  be that the commit added on oct 20th isn't correct. If you look in `~/.vscode/extensions` after running home-manager with that commit, you'll see that it's got a folder called "share" in there, because the vscode extensions are installed from share/... not top-level which the linking assumes.

At least that's the case on Linux.

**Comment by rycee** [comment]
I've merged @pasqui23's fix. Please give it a try with the latest master!

**Comment by pradyuman** [comment]
Looks like it's working! Thanks for the fix @pasqui23.
