### ISSUE TITLE
Q? : Eclipse with egit & m2e included

### ISSUE THREAD

**Issue by PierreR** [rycee/home-manager#890]
What is the idiomatic way to get egit & m2e plugins within Eclipse ?

I believe these two are not part of the eclipse platform (correct me if I am wrong).

I currently need to upload them on the command line (but this is a real pain).

It looks like egit is part of eclipse-ide.

Is there an good alternative to both plugins ?

Thanks for your help.

**Comment by rycee** [comment]
Like I said on IRC there unfortunately is no idiomatic way to install these plugins. I've never found a good way to package them (at least the m2e one, the egit one might be pretty easy to package since a zipped update site seems to be provided on the Eclipse site).

I no longer use Eclipse but when I did I would install m2e manually.

**Comment by PierreR** [comment]
@rycee Thanks for your input.
