### ISSUE TITLE
attribute 'runtimeShell' missing during install

### ISSUE THREAD

**Issue by sokoow** [rycee/home-manager#947]
Hi All,

I've just followed your install process and... got this:

```
$ nix-shell '<home-manager>' -A install

Creating initial Home Manager configuration...

Creating initial Home Manager generation...

error: attribute 'runtimeShell' missing, at /nix/store/d2idfmr93gxzdfnxzjr13vm6lz4hgj3p-home-manager/home-manager/modules/home-environment.nix:389:15
(use '--show-trace' to show detailed location information)

There are 94 unread and relevant news items.
Read them by running the command 'home-manager news'.
```

I'm using nixos 18.03 - what am I doing wrong ?

**Comment by rycee** [comment]
Hmm, did you use the [release-18.03](https://github.com/rycee/home-manager/tree/release-18.03) branch of HM? But 18.03 is very old and hasn't been supported for over a year so I would strongly suggest upgrading your system.

Specifcally, I believe the `runtimeShell` variable was added in 19.03 or possibly 18.09.

**Comment by sokoow** [comment]
Right, Imma switching to unstable and/or 19.03+ then, thanks :)

**Comment by rycee** [comment]
19.09 is the current stable version of NixOS so I would recommend aiming for that one. I'm not sure how to best upgrade from 18.03 to 19.09, though since I believe at some point Nix 2 became a requirement and I suspect 18.03 uses Nix 1. If you have any difficulties with the upgrade feel free to ask in the #nixos IRC channel or on https://discourse.nixos.org/.
