### ISSUE TITLE
Feature request: Default programs

### ISSUE THREAD

**Issue by pmiddend** [rycee/home-manager#96]
It would be great if I could manage my default programs with home-manager. For example, I want to open PDF files with zathura (for example, when clicking on a PDF download in chrome). Most programs use `xdg-open file.pdf` to open files. Using
```
xdg-mime default zathura.desktop application/pdf
```
I can change the default program for pdfs to zathura. Otherwise, xdg-open "guesses" and chooses gimp (!) on my system.

What the above `xdg-mime` command generates or adds is a file `$HOME/.config/mimeapps.list`, like so:
```
[Default Applications]
application/pdf=zathura.desktop
```
We could just generate this file using home-manager. The nix-pseudocode for this could be:
```
{
  defaultPrograms."application/pdf" = "${pkgs.zathura}/share/applications/zathura.desktop";
}
```

Does this sound like a thing for home-manager?

I have practically zero experience with nix, so I _might_ try this myself as an exercise. However, I'd be glad, too, if somebody else would tackle this problem.

**Comment by rycee** [comment]
Yeah, I think this is a reasonable thing for Home Manager to support. I'm thinking it is not as straight forward as just letting HM manage the `$XDG_CONFIG_HOME/mimeapps.list` since that would make it read only and I imagine most desktop managers would be unhappy with that. Instead I guess a `default-application.nix` module would need to add calls to `xdg-mime` tool in the activation script…

**Comment by teto** [comment]
Back on ubuntu I found myself fighting quite a bit with this because some xdg-utilities would keep overriding my mimeapps.list symlink to my dotfiles. (sent a patch for it, never got any news).

Here are some relevant links
https://askubuntu.com/questions/16580/where-are-file-associations-stored
https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-1.0.1.html
So apparently Desktops should use `$XDG_CONFIG_HOME/$desktop-mimeapps.list` but I actually doubt any does.

**Comment by teto** [comment]
I've had xdg-open use the wrong browser for some reason. Apparently there are many mime for x-scheme-handler which are better set via `XDG_UTILS_DEBUG_LEVEL=10 xdg-settings set default-web-browser firefox.desktop`

Sorry if it's more a memo to myself but I believe one could resort to  `activation`  in home-manager like for instance:
```
home.activation.checkXmonad = dagEntryBefore [ "linkGeneration" ] ''
xdg-settings set default-web-browser firefox.desktop
      '';
```

**Comment by pmiddend** [comment]
Your memo is appreciated, since I had the problem of the wrong default browser, too. :)

**Comment by wedens** [comment]
I've been managing `~/.config/mimeapps.list` manually for about a year on Arch Linux without DM and I haven't noticed any problems. But perhaps its distro or even DM specific.

I'd like to see original proposal implemented though (with a fat warning that it may not work well with some configurations).

**Comment by Jomik** [comment]
If what @wedens says is the case, and we can have it `read-only`, then it should be easy enough to manage already using `xdgConfigFile."mimeapps.list".text = " ... "`.
Obviously this would be per user, and perhaps we'd want the options of having something like `programs.firefox.default = true;`

**Comment by spinus** [comment]
@pmiddend I guess this issue can be closed as xdg-mime-apps is here?

**Comment by pmiddend** [comment]
Correct, thanks!
